title: <span style="text-align:center;">Dr. Su Leen Wong</span> # website title
logo: "/assets/images/logo.png?raw=true" # logo
description: > # your text below
  <span style="color:#1c1c20;">Thanks for dropping by my page!</span> <br><br>
  I'm currently a Data Science student at neue fische.<br><br>
  I really enjoy learning new tools, exploring data to help solve problems, and helping others understand ideas and data.
  <br>


theme: jekyll-theme-minimal
#google_analytics: G-ESQ433ZWGK # Google Analytics tracking ID
