title: <span style="text-align:center;">Dr. Su Leen Wong</span> # website title
logo: "/assets/images/logo.png?raw=true" # logo
description: > # your text below
  I'm currently a Data Science student at neuefische - School and Pool for Digital Talent.
  <br><br>
  I am an experienced lead research scientist specialized in developing analytical models for materials science. 
  <br><br>
  I hold a PhD in Mechanical Engineering, with 7+ years experience in data-driven research, code development and project management.
  <br><br>
  <br>


theme: jekyll-theme-minimal
#google_analytics: G-ESQ433ZWGK # Google Analytics tracking ID
