title: <span style="text-align:center;">Dr. Su Leen Wong</span> # website title
logo: "/assets/images/logo.png?raw=true" # logo
description: > # your text below
  <span style="color:#1c1c20;">Thanks for dropping by my page!</span>
  <br><br>
  I'm currently a Data Science student at neue fische.
  <br><br>
  I am an experienced lead research scientist specialized in developing analytical models for materials science. 
  I hold a PhD in Mechanical Engineering, with 8+ years experience in data-driven research, code development and project management.
  <br><br>
  <br>


theme: jekyll-theme-minimal
#google_analytics: G-ESQ433ZWGK # Google Analytics tracking ID
